const { DataTypes, UUIDV4 } = require("sequelize");
module.exports=(sequelize)=>{
    sequelize.define('Usuario',{
        id_Usuario:{
            type: DataTypes.UUID,
            primaryKey:true,
            allowNull:false,
            defaultValue:UUIDV4
        },
        correo:{
            type:DataTypes.STRING,
            allowNull:false
        },
        image:{
            type:DataTypes.TEXT,
            allowNull:true,
        },
        celular:{
            type:DataTypes.INTEGER,
            allowNull:true
        },
        nombres:{
            type:DataTypes.STRING,
            allowNull:false
        },
        apellidos:{
            type: DataTypes.STRING,
            allowNull:false
        },
        fecha_Nacimiento:{
            type:DataTypes.DATE,
            allowNull:true
        },
        ci:{
            type:DataTypes.STRING,
            allowNull:false
        },
        password:{
            type:DataTypes.STRING,
            allowNull:false
        },
        rol:{
            type:DataTypes.STRING,
            allowNull:false,
            defaultValue:'Client'
        },
        estado:{
            type:DataTypes.BOOLEAN,
            allowNull:false,
            defaultValue: true
        },
        verificacion:{
            type: DataTypes.STRING,
            allowNull:false,
            defaultValue:UUIDV4
        }
    }
    );
}